export { default as HtmlIcon } from './TechsIcons/HtmlIcon';
export { default as JsIcon } from './TechsIcons/JsIcon';
export { default as NodeIcon } from './TechsIcons/NodeIcon';
export { default as ReactIcon } from './TechsIcons/ReactIcon';
export { default as ScssIcon } from './TechsIcons/ScssIcon';
export { default as ExpressIcon } from './TechsIcons/ExpressIcon';
export { default as CssIcon } from './TechsIcons/CssIcon';
export { default as GitIcon } from './ToolsIcons/GitIcon';
export { default as InsomniaIcon } from './ToolsIcons/InsomniaIcon';
export { default as MongoIcon } from './ToolsIcons/MongoIcon';
export { default as NpmIcon } from './ToolsIcons/NpmIcon';
export { default as ViteIcon } from './ToolsIcons/ViteIcon';
export { default as GitHubIcon } from './ExtraIcons/GitHubIcon';
export { default as LinkedinIcon } from './ExtraIcons/LinkedinIcon';
export { default as CurriculumIcon } from './ExtraIcons/CurriculumIcon';
export { default as JwtIcon } from './ToolsIcons/JwtIcon';
export { default as BoltIcon } from './ExtraIcons/BoltIcon';
export { default as CodeIcon } from './ExtraIcons/CodeIcon';
export { default as PhoneIcon } from './ExtraIcons/PhoneIcon'